### ISSUE TITLE
Meaning of topN coordinates?

### ISSUE THREAD

**Issue by 1jsingh** [nicolalandro/ntsnet-cub200#4]
Can you please explain the significance of top N coordinates? Are these bbox predictions?

**Comment by nicolalandro** [comment]
![](https://raw.githubusercontent.com/nicolalandro/ntsnet-cub200/master/images/nts-net.png)
As you can see in this figure the Navigator extract 3 crops I1, I2 and I3. The top N coordinates are the coordinates extracted from the navigator. In the code at [nts_net/config.py](https://github.com/nicolalandro/ntsnet-cub200/blob/master/nts_net/config.py)  is 
 $CAT_NUM=4$ this 4 crop are chose from 6 that are $PROPOSAL_NUM=6$

**Comment by 1jsingh** [comment]
I was wondering whether there it is possible to predict the overall bird bounding box, from these predictions?

**Comment by nicolalandro** [comment]
It is possible if you add something to force it. It is unsupervised, and the purpose is to do attention. So the bbox are component, detail of the subject for example in bird can be beak or a wing. It does not detect the bird. For this task exist other networks.

**Comment by 1jsingh** [comment]
Thanks!
