### ISSUE TITLE
Request for the descriptions for each image

### ISSUE THREAD

**Issue by Ddiamondgold** [nicolalandro/ntsnet-cub200#5]
Hi,

In addition to the original Caltech-UCSD Birds-200-2011 Dataset, you mentioned in the paper that you also collected 10 description sentences for each images with MTurk. May I ask if the descriptions data is available for public use and may I have the download link if possible? Thanks!

**Comment by nicolalandro** [comment]
You can find that data in this release: https://github.com/nicolalandro/ntsnet-cub200/releases/tag/0.3

**Comment by Ddiamondgold** [comment]
Thanks!
